### ISSUE TITLE
ExistDb.__init__ does not work well without Django settings

### ISSUE THREAD

**Issue by lddubeau** [emory-libraries/eulexistdb#3]
Version 0.20.1

I understood Django usage to be optional. However, if I run this code:

```
import os

from eulexistdb.db import ExistDB

password = os.environ["PASS"]
db = ExistDB("http://localhost:8088/", "admin", password)
```

I get this error message which would strongly suggest that Django settings are a must:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    password)
  File ".venv/local/lib/python2.7/site-packages/eulexistdb/db.py", line 172, in __init__
    timeout = getattr(settings, 'EXISTDB_TIMEOUT', None)
  File ".venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File ".venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting EXISTDB_TIMEOUT, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```

If I ignore the suggestion about the Django settings and add `timeout=None` to try to work around it, I get:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    db = ExistDB("http://localhost:8088/", "admin", password, timeout=None)
  File ".venv/local/lib/python2.7/site-packages/eulexistdb/db.py", line 188, in __init__
    keep_alive = getattr(settings, 'EXISTDB_SESSION_KEEP_ALIVE', None)
UnboundLocalError: local variable 'settings' referenced before assignment
```

It is not until I have this that the code works without failure: `ExistDB("http://localhost:8088/", "admin", password, timeout=None, keep_alive=True)`. (I don't know whether `keep_alive=True` makes sense at all.)

**Comment by rlskoeser** [comment]
@lddubeau yeah, django is supposed to be optional.  Looks like I messed something up.  I'll take a look.

**Comment by rlskoeser** [comment]
Closing, fixes will be in the next release
